services:
  python:
    build:
      context: .
    ports: 
      - 8000:8000
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY} 
  postgres:
    image: postgres:17.6 
    environment:
      POSTGRES_PASSWORD: password 
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  qdrant:
    image: qdrant/qdrant:dev
    ports: 
      - 6333:6333
      - 6334:6334 
    volumes:
      - qdrant_data:/qdrant/storage
volumes:
  postgres_data:
  qdrant_data:

configs:
  qdrant_config:
    content: |
      log_level: INFO