name: Tests 

on: [pull_request, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Install uv 
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.17
      - name: Install dependencies
        run: uv sync --frozen 
      - name: Run Tests 
        run: uv run pytest tests